-- Library content for maritime Washington (Olympic rain shadow), from the
-- 2026-09 WSU-primary research. Written for a CIDER orchard: cosmetic
-- damage is called out as ignorable, and the pests that actually cost
-- money (internal feeders, rot pathways, defoliators) lead.

INSERT INTO pest_library
  (key, name, scientific_name, category, prevalence, summary, symptoms, lookalikes,
   lifecycle, timing, monitoring, management, cider_note, refs, sort_order)
VALUES

('apple_anthracnose', 'Apple anthracnose', 'Neofabraea malicorticis', 'disease', 'high',
 'The signature canker disease west of the Cascades, and the one most likely to shape your whole program.',
 'Small purple-red spots on young bark in autumn that expand into sunken, oval, target-shaped cankers with cracked margins. Cankers stretch along the limb and produce cream-coloured spore masses in wet weather. Infected fruit develops bull''s-eye rot in storage.',
 'European canker looks similar but its cankers are more ragged and concentric, often centred on a pruning wound or bud scar, and it produces bright red-orange fruiting bodies in winter. Anthracnose cankers are smoother-edged and more clearly target-shaped.',
 'Spores are released through autumn and winter rains and infect through bark, especially young wood. Cankers develop over the following season and sporulate the next autumn — a full year behind the infection.',
 'Excise in DRY weather, autumn through winter. Copper goes on before the autumn rains begin.',
 'Scout monthly, walking limbs rather than scanning from a distance. Count cankers per stem — the count drives the decision.',
 'Knife-first: this is the key finding. WSU''s own fungicide trial failed here (77% canker growth despite sprays), so cutting is the program and copper is support. Carve out each canker with a quarter-inch margin of healthy bark, sterilise the blade between cankers, and paint the wound with fresh Bordeaux paste (10-10-100). Remove any stem carrying four or more cankers. Burn trees with four or more on most branches — they are an inoculum source for the whole block.',
 'Matters twice over: the canker phase costs you wood, and the same fungus is bull''s-eye rot on stored fruit.',
 ARRAY['WSU FS295E','Garton 2019 (WSU fungicide trial)'], 1),

('apple_scab', 'Apple scab', 'Venturia inaequalis', 'disease', 'high',
 'The classic maritime disease — driven by spring wetness, and cheapest to control on the orchard floor in autumn.',
 'Olive-green velvety blotches on leaves that turn brown-black and corky; infected leaves yellow and drop. Fruit lesions start olive and become rough, cracked and scabby. Heavy infection defoliates trees by midsummer.',
 'Early-season scab lesions can be confused with sooty blotch, but sooty blotch is a superficial smudge that rubs off and appears late in the season on fruit only.',
 'Overwinters in fallen infected leaves. Spring rain releases ascospores onto emerging tissue; secondary conidia then cycle through the season on wet foliage.',
 'Primary season runs green tip through about two weeks past the last primary infection. Infection needs a Mills wetness period — roughly 6 to 11 hours wet at 50 to 60°F.',
 'Watch wetness periods rather than the calendar. Check the undersides of the oldest leaves first, and inspect fruitlets after any long wet stretch.',
 'Autumn leaf-litter sanitation is the best value in the whole program: flail mow the leaves and apply 5% urea to cut overwintering inoculum by 50 to 80%. In spring use copper at half-inch green, then lime sulfur on the wetness periods. Critically, wettable sulfur does NOT control scab west of the Cascades — lime sulfur is the backbone here.',
 'WSU calls mild scab "of little consequence" for press fruit. Control it for tree vigour and defoliation, not cosmetics.',
 ARRAY['WSU EM066E','PNW Plant Disease Handbook'], 2),

('european_canker', 'European canker', 'Neonectria ditissima', 'disease', 'moderate',
 'Serious in wetter maritime Washington; your rain shadow probably keeps it marginal, but it is the one to watch with real uncertainty.',
 'Sunken, ragged cankers with concentric rings of callus, usually centred on a wound, bud scar or pruning cut. Bright red-orange fruiting bodies appear on cankers in winter. Girdled limbs die back.',
 'Anthracnose — see that entry. European canker''s red-orange winter fruiting bodies are the reliable tell.',
 'Spores infect through fresh wounds, especially leaf scars at leaf fall and pruning cuts. Cankers enlarge over years.',
 'Highest risk at leaf fall and through winter. Prune in dry weather, never before rain.',
 'Inspect pruning wounds and leaf-scar zones from late autumn. Track whether your site actually meets the climate threshold: more than 30% rain-days in a month plus 8 or more hours at 52 to 60°F. In the rain shadow that may only happen November to January.',
 'Excise as for anthracnose, and protect leaf scars with copper at leaf fall. Avoid pruning into wet weather.',
 'Costs you structural wood rather than fruit quality.',
 ARRAY['NIAB leaf-fall copper cadence','WSU maritime guidance'], 3),

('phytophthora', 'Phytophthora root & crown rot', 'Phytophthora cactorum', 'disease', 'moderate',
 'Not a general regional threat so much as a rootstock-specific one — and your EMLA 106 block sits squarely in the risk window.',
 'Trees decline slowly: sparse pale foliage, poor growth, early autumn colour, then sudden collapse. Bark at and just below the soil line turns dark and slimy; cutting it reveals an orange-brown margin against healthy white wood.',
 'Looks like general decline or drought stress from a distance. The diagnostic is cutting bark at the crown.',
 'A soil-borne water mould. Needs saturated soil to infect; a few days of standing water is enough.',
 'Risk is highest in the wet season and wherever water sits. Treat preventively — recovery is rare once decline is visible.',
 'Check crowns of susceptible rootstocks each winter, especially in low spots and after wet stretches.',
 'Drainage first, everything else second. Keep graft unions dry and well above soil, pull mulch back off trunks, and avoid irrigating against the trunk. A phosphonate can protect high-value trees. Your EMLA 106 trees are highly susceptible and in year 5 of the classic 3-to-8-year failure window; M.111 is intermediate; G.890 is your best-armoured rootstock.',
 'A dead tree is the cost — no fruit-quality dimension.',
 ARRAY['WSU orchard rootstock guidance'], 4),

('powdery_mildew', 'Powdery mildew', 'Podosphaera leucotricha', 'disease', 'moderate',
 'The one disease your dry site actively favours — it does not need free water, unlike scab.',
 'White-grey felty growth on shoot tips, leaf undersides and blossoms. Affected leaves are narrow, crinkled and folded upward. Infected shoots are stunted with silvered bark. Fruit shows a fine net-like russet.',
 'Early-season mildew on shoot tips can be mistaken for herbicide or frost injury; look for the felty white coating.',
 'Overwinters inside dormant buds, so infected shoots produce infected growth the following spring.',
 'Prune out silvered, infected shoot tips during dormancy — the overwintering source. Protect new growth from green tip through summer.',
 'Look at terminal shoots on the most vigorous trees; mildew follows soft growth.',
 'Remove infected shoot tips in winter, then sulfur through the season — wettable sulfur works well here even though it fails on scab. Remember the 14-day gap either side of any oil application.',
 'Russeting is cosmetic and irrelevant to cider. Control it for shoot vigour, not appearance.',
 ARRAY['WSU Hortsense'], 5),

('bulls_eye_rot', 'Bull''s-eye rot', 'Neofabraea spp.', 'disease', 'moderate',
 'The fruit-and-storage phase of the same fungus that causes anthracnose cankers.',
 'Flat or slightly sunken brown circular lesions with a paler centre and darker ring — the bull''s-eye. Usually appears weeks into storage, not in the orchard.',
 'Other storage rots are softer and more watery; bull''s-eye stays firm with a distinct ring.',
 'Fruit is infected in the orchard by spores from bark cankers, then the rot develops slowly in cold storage.',
 'Infection happens in autumn rains before harvest; symptoms show up after weeks in storage.',
 'Check stored fruit at 3 and 6 weeks. A spike in bull''s-eye rot is a direct signal that canker pressure in the block is high.',
 'Control the cankers — see apple anthracnose. Orchard sanitation pays twice here.',
 'Directly relevant: rotten fruit cannot go in the press, and heavy loss shows up as shrink between harvest and pressing.',
 ARRAY['WSU FS295E'], 6),

('blue_mold', 'Blue mold (and the patulin problem)', 'Penicillium expansum', 'disease', 'moderate',
 'The one rot with a food-safety dimension for a cidery, because it produces patulin.',
 'Soft, watery light-brown rot that collapses easily under a thumb, with blue-green powdery spore masses on the surface. Sharply defined margin between rotten and sound tissue.',
 'Grey mold (Botrytis) is similar but produces grey-brown fuzzy growth rather than blue-green powder.',
 'A wound pathogen: it enters through punctures, stem punctures, bruises and insect holes, then spreads in storage and in water.',
 'Harvest and post-harvest. Drops and bruised fruit are the reservoir.',
 'Inspect bins before pressing. Any fruit off the ground deserves particular scrutiny.',
 'Handle fruit gently, cull drops and punctured fruit, and keep bins and wash water clean. Controlling codling moth and apple maggot matters here too — every larval entry hole is a doorway for this fungus.',
 'This is the one place where "rot-free" is a food-safety rule and not an aesthetic preference: P. expansum produces patulin, a mycotoxin with an FDA action level in apple juice. Rotten fruit does not belong in the press, full stop.',
 ARRAY['FDA patulin guidance','WSU postharvest'], 7),

('sooty_blotch_flyspeck', 'Sooty blotch & flyspeck', 'complex of fungi', 'disease', 'low',
 'Cosmetic surface fungi. Named here mostly so you can confidently ignore them.',
 'Smudgy olive-grey blotches (sooty blotch) and tight clusters of tiny black dots (flyspeck) on the fruit surface late in the season. Both sit on the skin only.',
 'Unlike scab, these rub off with a cloth and never break the skin.',
 'Favoured by warm, humid late summers; colonises fruit surfaces in the weeks before harvest.',
 'Late season only.',
 'No monitoring needed for cider.',
 'Improve air movement through pruning if it bothers you. Do not spend a spray on it.',
 'Completely irrelevant to fermented product. Skip it.',
 ARRAY['WSU Hortsense'], 20),

('fire_blight', 'Fire blight — not a problem here', 'Erwinia amylovora', 'disease', 'absent',
 'Included so you can stop planning for it: fire blight is not a proven problem west of the Cascades.',
 'Blossoms and shoots blacken suddenly and wilt into a shepherd''s crook, looking scorched. Amber ooze on infected wood in warm weather.',
 'Winter injury and Pseudomonas blast can look similar in spring; both are far more likely here.',
 'Bacterial, spread by rain, insects and pruning tools during warm wet bloom.',
 'Bloom, during warm wet weather — conditions your bloom season rarely provides.',
 'No routine monitoring warranted here. Keep it in mind only if the region changes.',
 'No fire-blight line in your program. Worth knowing your tripwire cultivars if it ever arrives: Brown Snout and Ashmead''s Kernel showed 90-100% mortality in a Nova Scotia trial and would be the first casualties.',
 'A genuine freedom: the bittersweets'' poor fire-blight ratings are irrelevant here, which widens your planting choices considerably.',
 ARRAY['WSU Hortsense','owner field confirmation 2026-09'], 30),

('apple_maggot', 'Apple maggot', 'Rhagoletis pomonella', 'insect', 'high',
 'WSU calls it by far the most serious insect west of the Cascades — ahead of codling moth, which surprises growers who read eastern guides.',
 'Fruit surface shows small dimpled stings where eggs were laid. Inside, winding brown tunnels run through the flesh, and fruit breaks down early and drops.',
 'Codling moth leaves a single clean entry hole with frass at the surface and tunnels to the core; apple maggot tunnels wander through the flesh with no frass.',
 'One generation. Pupae overwinter in the soil, adults emerge through summer, lay eggs under the fruit skin, larvae tunnel and drop with the fruit to pupate.',
 'Adults emerge from about early July and fly into autumn. Trapping decisions are made on catches, not dates.',
 'Red sphere traps only. Colour traps mislead here because the snowberry maggot is field-indistinguishable and abundant on the Peninsula. Hang traps at the perimeter first — Prokopy perimeter trapping — and let catches drive the response.',
 'The highest-leverage action is not a spray: remove wild apple and hawthorn within a quarter to half mile, because they are the reservoir that reinfests you every year. Kaolin clay works as an oviposition deterrent. Spinosad is the organic material option. Note you are inside the Clallam County apple-maggot quarantine, so fruit, pomace, prunings and dripline soil cannot move to the pest-free area of central and eastern Washington without a WSDA permit.',
 'Infested fruit is a direct loss and an entry point for blue mold. This is the pest most likely to cost you tonnage.',
 ARRAY['WSU EB0937','WAC 16-470-105','Prokopy perimeter trapping'], 8),

('codling_moth', 'Codling moth', 'Cydia pomonella', 'insect', 'high',
 'The classic wormy-apple pest — two generations here, and timed by degree days rather than the calendar.',
 'A single round entry hole, often at the calyx end, packed with reddish-brown frass. Tunnelling runs straight to the core and the seeds are eaten.',
 'Apple maggot tunnels wander through the flesh and leave no frass. Leafrollers feed on the surface without tunnelling to the core.',
 'Two generations. Overwinters as mature larvae in cocoons under bark, pupates in spring, adults lay eggs on fruit and leaves, larvae bore into fruit.',
 'Because you are north of 46°N, use the NO-BIOFIX degree-day model accumulating from January 1: oil as an ovicide at 375 DD, first cover spray at 425 DD for first-generation hatch, and second generation around 1400 DD.',
 'Pheromone traps confirm flight but do not set the timing here — the degree-day model does. The weather engine already accumulates what this needs.',
 'CpGV (granulosis virus) is the organic backbone, but resistance is documented in Washington, so rotate strains and do not rely on one product. Spinosad is the step up. Mating disruption is not viable at your acreage — it needs scale to work. Horticultural oil at 375 DD smothers eggs.',
 'Every entry hole is a doorway for blue mold and patulin, so this matters more for a cidery than the cosmetic damage suggests.',
 ARRAY['WSU codling moth DD model','WSU EM117E'], 9),

('leafrollers', 'Leafrollers', 'Choristoneura, Pandemis, Archips spp.', 'insect', 'high',
 'Consistently present west-side. Usually a vigour and fruit-scarring problem rather than a crop-destroying one.',
 'Leaves rolled or webbed shut with silk. Open one and a green caterpillar wriggles backward violently or drops on a thread. Fruit shows shallow surface scars where larvae fed against a leaf.',
 'Rosy apple aphid also curls leaves, but there is NO silk webbing and opening the leaf reveals clusters of small purplish-grey aphids instead of a caterpillar. This is the single most common mix-up, and the treatments do not overlap at all.',
 'One to two generations depending on species. Overwinters as small larvae in bark crevices, becoming active as growth starts.',
 'Target small larvae. Once they are large and well protected inside rolled leaves, sprays work poorly.',
 'Beat trays under limbs in spring, and simply count rolled leaves on a set number of shoots per tree.',
 'Bt (Dipel) on small larvae is effective, OMRI-listed and harmless to the predators this program depends on — timing matters far more than product choice. Spinosad is the step up for heavy pressure. Overwintering larvae are also exposed to delayed-dormant oil.',
 'Surface scarring is cosmetic and irrelevant to cider. Treat for defoliation and vigour.',
 ARRAY['WSU leafroller guidance'], 10),

('rosy_apple_aphid', 'Rosy apple aphid', 'Dysaphis plantaginea', 'insect', 'moderate',
 'The other thing people mean by "leaf curler" — and the control window closes early.',
 'Leaves curl tightly and crumple, often reddish or distorted, usually at shoot tips. Inside the curl are clusters of small purplish-grey aphids with a waxy bloom. Fruit on affected spurs stays small, hard and misshapen — "aphid apples".',
 'Leafrollers also curl leaves but leave silk webbing and contain a caterpillar. Green apple aphid causes milder curling and does not distort fruit.',
 'Overwinters as eggs on apple, builds up during spring on shoot tips, then migrates to narrow-leaf plantain for the summer and returns in autumn.',
 'The window is delayed dormant through early pre-bloom. Once the leaves have curled shut, contact materials cannot reach the aphids inside — which is why mid-season treatment feels futile.',
 'Inspect shoot tips from green tip to pink. Heavy curl later in the season usually means you missed the window.',
 'Delayed-dormant oil is the main control. Insecticidal soap works only while aphids are exposed. Conserve natural enemies — these aphids are heavily predated when broad-spectrum sprays are avoided. Controlling plantain in and around the orchard removes the summer host.',
 'Fruit distortion means small, hard fruit that presses poorly. Worth controlling properly at the right time.',
 ARRAY['WSU Hortsense','PNW insect handbook'], 11),

('woolly_apple_aphid', 'Woolly apple aphid', 'Eriosoma lanigerum', 'insect', 'moderate',
 'A long-term orchard-design pest rather than a spray target — mild winters here favour it.',
 'Conspicuous white cottony masses on pruning wounds, burr knots and limb crotches. Underground, colonies cause swollen galls on roots. Heavy infestation weakens trees and honeydew leads to sooty mould.',
 'The white wool is distinctive; mealybugs are rare on apple here.',
 'Overwinters on roots and in bark crevices, moving up into the canopy through the season. Mild winters improve survival.',
 'Colonies build through summer. Root damage accumulates over years.',
 'Check pruning wounds and burr knots, and look for wool at the base of trunks. On suspect trees, examine roots when planting or replacing.',
 'Oils do NOT penetrate the waxy wool, so the real control is biological: conserve the parasitoid Aphelinus mali and earwigs, both WSU-endorsed as effective predators — which means not spraying broad-spectrum materials that wipe them out. Rootstock is the durable answer: G.890 is resistant, while MM.111 and EMLA 106 resistance may be breaking down. M.111''s heavy burr knots also give colonies a foothold.',
 'Indirect cost through tree vigour, not fruit quality.',
 ARRAY['WSU EM117E','WSU biological control guidance'], 12),

('apple_ermine_moth', 'Apple ermine moth', 'Yponomeuta malinellus', 'insect', 'moderate',
 'A genuine Puget Sound speciality — established in western Washington since the 1980s and largely missing from eastern-Washington guides.',
 'Conspicuous communal silk tents full of gregarious larvae, which can strip whole branches of leaves. Adults are white with black dots.',
 'Tent caterpillar tents are coarser and sit in branch crotches; ermine moth webbing envelops the foliage it is feeding on.',
 'One generation. Overwinters as tiny larvae under a shield on twigs, emerging to feed as leaves expand.',
 'Larvae emerge with new growth in spring — treat while they are small and before the webbing thickens.',
 'Easy to spot: scan for webbing from a distance in late spring.',
 'Bt while larvae are small. Physically removing and destroying tents works well at small orchard scale.',
 'Defoliation costs vigour; no direct fruit-quality effect.',
 ARRAY['WSU Hortsense'], 13),

('tent_caterpillar', 'Tent caterpillars & winter moth', 'Malacosoma spp., Operophtera brumata', 'insect', 'low',
 'Episodic defoliators — a problem in outbreak years, invisible in most others.',
 'Tent caterpillars build dense silk tents in branch crotches and feed in groups. Winter moth larvae are small green loopers that feed in expanding buds and on young leaves, often before you notice them.',
 'Winter moth loopers move with a characteristic inch-worm gait; leafroller larvae wriggle backward instead.',
 'Both overwinter as eggs and hatch as buds break, so damage lands on the most vulnerable tissue.',
 'Bud break through early leaf expansion.',
 'Watch for tents from a distance in spring; for winter moth, check expanding buds for tiny loopers.',
 'Bt on small larvae. Prune out and destroy tents. Neither warrants a standing program in a normal year.',
 'Vigour only.',
 ARRAY['WSU Hortsense'], 14),

('yellowjackets', 'Yellowjackets & wasps', 'Vespula spp.', 'insect', 'moderate',
 'A harvest-season problem specific to cider work rather than a tree pest.',
 'Wasps working ripe and damaged fruit, hollowing it out. Numbers build sharply in late summer.',
 'Honeybees do not damage sound fruit; wasps enlarge existing wounds.',
 'Colonies grow through summer and peak at harvest, when they switch to sugar.',
 'Late summer through harvest.',
 'You will notice them without trying. Track which blocks and bins are affected.',
 'Remove drops and damaged fruit promptly — they are the attractant. Bait traps away from the picking area. Avoid pressing wasp-worked fruit.',
 'Both a fruit-quality issue and a picking-crew safety issue at exactly the busiest time of year.',
 ARRAY['WSU Hortsense'], 15),

('european_earwig', 'European earwig — mostly an ally', 'Forficula auricularia', 'beneficial', 'beneficial',
 'Listed deliberately as a beneficial: earwigs are among your best woolly apple aphid predators.',
 'Familiar pincered insects sheltering in bark crevices and fruit clusters by day. Occasionally chew shallow shelter holes in fruit.',
 'Damage is sometimes blamed on earwigs when the real culprit is a wasp or bird wound that earwigs then shelter in.',
 'One generation, with females tending eggs in soil chambers over winter.',
 'Active spring through autumn.',
 'Roll-up traps under limbs if you want a population estimate.',
 'Do NOT spray them out. WSU endorses earwigs as effective predators of woolly apple aphid and aphids generally, and broad-spectrum insecticides that remove them tend to make aphid problems worse.',
 'Minor shelter damage is irrelevant to cider; the predation is worth far more.',
 ARRAY['WSU biological control guidance'], 16),

('mites', 'Spider mites', 'Tetranychus and Panonychus spp.', 'mite', 'low',
 'Usually a self-inflicted problem — mite flare-ups follow broad-spectrum sprays that removed their predators.',
 'Fine stippling and bronzing of leaves, sometimes light webbing on the undersides. Heavy infestation causes early leaf drop.',
 'Nutrient deficiency and drought stress cause similar bronzing without stippling or webbing.',
 'Multiple overlapping generations in hot dry weather; suppressed by cool maritime conditions.',
 'Mid to late summer, and only in hot dry stretches.',
 'Check leaf undersides with a hand lens during any hot dry spell.',
 'The best control is not creating the problem: protect predatory mites by avoiding broad-spectrum insecticides. Oil and insecticidal soap help if a flare does occur.',
 'Vigour only — irrelevant to fruit quality.',
 ARRAY['PNW insect handbook'], 17)

ON CONFLICT (key) DO NOTHING;
